
language: swift
osx_image: xcode10

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8


before_install:
    - env
    - locale
#    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-document --quiet
    - pod --version
    - pod repo remove master
    - pod setup --silent > /dev/null
    - pod repo update --silent
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script: 
   - set -o pipefail

   - echo Build as framework
   - xcodebuild clean build -project fbCharm.xcodeproj -scheme fbCharm -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c

#after_success:
#    - bash <(curl -s https://codecov.io/bash) 
