# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

workspace 'fbCharmDemo.xcworkspace'
project 'fbCharmDemo.xcodeproj'

target 'fbCharmDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for fbCharmDemo
  pod 'fbCharm'
end
